### ISSUE TITLE
Modrinth shenanigans

### ISSUE THREAD

**Issue by FnigePython** [Null-MC/Shrimple#1]
Within the versions, it shows that it is supports optifine despite the description saying that it only supports iris. Which one is correct?

![image](https://user-images.githubusercontent.com/35159947/227442827-2e285b7e-6203-4f78-a6a9-040f5a414638.png)
![image](https://user-images.githubusercontent.com/35159947/227442851-7f966ff1-5670-4678-a810-2a971995a7fa.png)

**Comment by null511** [comment]
I'll update the description, but it's a bit of both.

Basic features like FXAA, shadows, and sun/moon volumetric lighting work on Optifine.

Advanced features like colored lighting, ray-tracing, and cascaded shadow mapping require newer features that are only available on Iris.

**Comment by null511** [comment]
fixed with release 0.7
