### ISSUE TITLE
Emissive Ores

### ISSUE THREAD

**Issue by joeyak** [Null-MC/Shrimple#10]
Would it be possible to add an option to have emissive ores. Something like below. It's really the only thing I'm missing from other shaders.

![image](https://user-images.githubusercontent.com/27922090/232179602-45dd07e7-3fcf-40a0-9eb5-00b2b71a1b31.png)

**Comment by null511** [comment]
I don't have any plans to add hard-coded per-pixel emission. However you can easily get that effect by using an OldPBR or LabPBR resource pack. For example, I believe AVPBR supports emissive ores.

**Comment by joeyak** [comment]
Yeah that works now. Thanks!
