### ISSUE TITLE
All block textures are white when using any profile

### ISSUE THREAD

**Issue by EarthKone** [Null-MC/Shrimple#106]
Title. It's not a resource pack issue, it's only when I have shaders enabled
![image_2024-10-09_225359855](https://github.com/user-attachments/assets/cf585f66-b778-4eeb-85b1-67ad7bffe698)

**Comment by EarthKone** [comment]
The problem was Chunks Fade-In

**Comment by Legotier** [comment]
> The problem was Chunks Fade-In

Thank you my friend, you saved me hours of debugging :)
