### ISSUE TITLE
Text on signs doesn't show

### ISSUE THREAD

**Issue by Aeldit** [Null-MC/Shrimple#11]
When the shader is enabled using Iris 1.6.1, the texts on signs just doesn't show (see pictures):

Without shaders :
![2023-04-16_22 53 29](https://user-images.githubusercontent.com/81476169/232341632-2a69ae16-290a-442d-8c39-831a7767737e.png)

With the shader :
![2023-04-16_22 53 34](https://user-images.githubusercontent.com/81476169/232341644-c9096b1b-2efc-4f43-bd11-7086e3a462a7.png)

**Comment by null511** [comment]
Is this the latest code download from github, or a stable release?
 - if it's latest github, then that is an Iris bug that will hopefully be fixed in 1.6.2
 - if it's release, grab the latest github "download code" and it should be fine.

**Comment by Aeldit** [comment]
It was indeed a problem with the release version
