### ISSUE TITLE
Shaderpack failed to load with RTX profile on Linux and AMD

### ISSUE THREAD

**Issue by Buuugle** [Null-MC/Shrimple#112]
Hi!
When I try to enable the shaderpack with RTX profile, I get this error: "The shaderpack failed to load! Please report the error to the shader developer". Here's the error:
```
composite11.csh: composite11.csh: 0:349(30): error: variables of type sampler2D cannot be operands of the ?: operator
```
All the other profiles work fine.

Shaderpack version : 0.12 (the lastest in dev version downloaded from GitHub has the same issue)
Minecraft version : 1.21.4
Iris version : 1.8.4
Sodium version : 0.6.4
OS : Arch Linux
GPU : AMD RX 7800 XT
Mesa version : 24.3.1

**Comment by null511** [comment]
Sorry, this is specific to AMD gpu's (I use nvidia) so I didn't catch it. Should be fixed now in latest from github.

**Comment by Buuugle** [comment]
Thanks for the fix! Now I have a similar issue :
`composite12.fsh: composite12.fsh: 0:935(52): warning: `blockIdLast' used uninitialized
0:1221(33): warning: `lightRange' used uninitialized
0:1589(28): error: variables of type sampler2D cannot be operands of the ?: operator
0:1590(29): error: variables of type sampler2D cannot be operands of the ?: operator
`
I suppose you should replace all `?:` operators with `if` `else` wherever a sample2d object is involved, in all files. I can try to fix this on my end and make a pull request if it takes you too long to test this without an AMD GPU.

**Comment by Buuugle** [comment]
In the end, the only file to edit is `composite12.fsh`. Now the shader is loaded successfully :)
I made a pull request with this small fix!
