### ISSUE TITLE
How to download for Iris?

### ISSUE THREAD

**Issue by andreyrisukhin** [Null-MC/Shrimple#12]
Hello! Just a quick question, I am unfamiliar with how to download this shader project for use with Iris. Could I have some help?

Thank you! Saw this linked in the Iris discord, excited to try it. :-)

**Comment by DeadbushCarrot** [comment]
Here https://modrinth.com/shader/shrimple

**Comment by andreyrisukhin** [comment]
Thank you! Successfully installed, closing issue to mark this.
