### ISSUE TITLE
weird shadow filtering behavior at very high shadow map resolutions.

### ISSUE THREAD

**Issue by christopher317** [Null-MC/Shrimple#13]
![2023-05-02_18 08 57](https://user-images.githubusercontent.com/86526198/235804963-3ccc82de-69ac-4c63-a579-7f2aa7cae55b.png)
the shadow casted on the water looks normal and nice and sharp, but the shadow casted on land its way more bury than it should be, any idea whats going on? ( happens with both pcf and pcss )

shader config ( v0.8 ):
[Shrimple (replay preset).zip.txt](https://github.com/Null-MC/Shrimple/files/11378267/Shrimple.replay.preset.zip.txt)
( only occurs and shadow map res 8192 )

**Comment by null511** [comment]
Unless I'm misunderstanding your issue, that's how it should be; PCF & PCSS are both options for soft-shadows.
- PCF has a constant blur radius
- PCSS has a variable blur radius, which is sharp close to caster and blurry the further away it is.

However with water (or any translucent block) I cannot apply the same blurring, so they still have sharp shadows.

**Comment by christopher317** [comment]
i see, so i was just misunderstanding how the shader works.
its still weird how the blur radius appears to go up when changing the shadowmap res to 8192 compared to 4096.

whatever, at that point the issue i am thinking of is not what i described so il close the issue.
