### ISSUE TITLE
Shader just doesn't work, using latest iris

### ISSUE THREAD

**Issue by bisquickpancakemix** [Null-MC/Shrimple#15]
I've tried to use this shader but no matter what settings I use, using iris, it just does nothing. When applied it looks like I'm just playing the vanilla game. What's causing the issue ? I'm on fabric 1.19.4 and also using the latest fabric api

**Comment by null511** [comment]
I would need your error log to know what went wrong (~/.minecraft/logs/latest.txt)

Just to confirm, you're using Iris 1.6.2 or later right?

**Comment by bisquickpancakemix** [comment]
no, soium is broken and it broke the latest iris, 1.6.2 was pulled alongside 0.11 of sodium.

**Comment by null511** [comment]
No, that was 1.6.3 for sodium 0.4.11 that was pulled; and it's already been replaced with a 1.6.3 release for sodium 0.4.10

**Comment by bisquickpancakemix** [comment]
That was 1.6.2, if you read their description they even say it's a replacement for 1.6.2 that used to work with 0.11 of sodium. Regardless, I updated to that version of iris and shrimple shaders still *does nothing* I tried it again just now and my game looks vanilla

**Comment by bisquickpancakemix** [comment]
Nevermind, I deleted the shader from my shaderpacks folder and redownloaded it and it's working now.
