### ISSUE TITLE
Red Sky

### ISSUE THREAD

**Issue by n3cto** [Null-MC/Shrimple#2]
![Screenshot 2023-04-05 152904](https://user-images.githubusercontent.com/129965171/230095410-b1b2a44a-250c-49a8-8efd-4ca730d42f74.png)

I have this problem where the sky is just red? I'm on 1.19.2 and I really like this shader, because it performs so well, but this issue is really bugging me. Everytime I join a world or server it says:

[Shaders] Error: Invalid program "gbuffers_textured" [Shaders] Error: Invalid program "gbuffers_clouds" [Shaders] Error: Invalid program "gbuffers_hand_water"

Also, when I hold something in my hand and it's above a fence, it just becomes transparent

![Screenshot 2023-04-05 153228](https://user-images.githubusercontent.com/129965171/230096516-c93f63a3-2eaf-45ca-9838-78ee9a974ab0.png)

**Comment by FiNee13** [comment]
What's the version of Iris?

**Comment by n3cto** [comment]
I'm using OptiFine HD U I1 for 1.19.2.

**Comment by null511** [comment]
I don't use optifine much anymore now that Iris has more features, but I'll see if I can reproduce this on my end.

**Comment by null511** [comment]
It took me a good while to fix up, but Optifine should be working fine again with the latest github code download (not in releases yet)
