### ISSUE TITLE
Is there anyway to get this compatible with a Forge install?

### ISSUE THREAD

**Issue by bagenskiii** [Null-MC/Shrimple#22]
I'm not a fan of using Fabric. I feel as if it limits my options too much. Iris only works with Fabric but this shaderpack is everything I've been looking for. Would it be possible to make a version that works without Iris?

**Comment by null511** [comment]
Only if Optifine adds support for shader SSBO & custom images; otherwise best bet is waiting for Oculus to catch-up on Iris features.
