### ISSUE TITLE
Blue noise artifacting when using any profile option except for "Vanilla"

### ISSUE THREAD

**Issue by susrn** [Null-MC/Shrimple#31]
Using Iris on 1.19.2

Here's a screenshot for reference

![Screenshot_20230619_200529](https://github.com/Null-MC/Shrimple/assets/98364725/13938543-a0d2-4a4d-a9a6-cc201cc2e1f6)

[**Log file**](https://gist.github.com/susrn/28096be9173bac9b5c22e8f84173d359)

**Comment by null511** [comment]
This should only happen with Iris & 1.19.2. I've had that issue forever now, seems to be an Iris bug but I can't find it.
