### ISSUE TITLE
Black squares under entities with Vanilla profile

### ISSUE THREAD

**Issue by Gamerocker7000** [Null-MC/Shrimple#34]
Whenever I turn the profile to "Vanilla" There is no shadow under entities, only solid black squares. 
![2023-07-16_12 54 56](https://github.com/Null-MC/Shrimple/assets/94730840/e6619c27-bc6b-4963-b088-be09c7e50bf9)
![2023-07-16_12 55 00](https://github.com/Null-MC/Shrimple/assets/94730840/86bf9177-14bc-460f-96f7-dcd70670c430)

I'm simply using Sodium and Iris latest for 1.20.1 on fabric loader in these screenshots with no additional mods or resource packs.

OS: Windows 10
GPU: NVidia GeForce GTX 1060 3GB
CPU: Intel Core i-7 6700
RAM: 32gb 2133mhz

**Comment by christopher317** [comment]
i have the same issue, turning off entity shadows appears to fix the issue and so does turning on raster shadows ( even if the brightness is set to 100% so they don't appear to render ) for now your best bet is to just turn off entity shadows until null sees this.

**Comment by null511** [comment]
This should be fixed now in the latest main branch, but not yet in a release.
