### ISSUE TITLE
Strange Reflection/Effect

### ISSUE THREAD

**Issue by TwinShards** [Null-MC/Shrimple#48]
*With colored ray-traced turned on, other 2 options do not cause this effect

![2023-09-17_23 17 31](https://github.com/Null-MC/Shrimple/assets/29926123/8a476137-156e-4db0-83d0-de212d9f0ea4)

**Comment by null511** [comment]
That is the specular reflection of the portal light, and intended. The lights are currently treated as spheres, since cubic lights caused other issues.
