### ISSUE TITLE
Game crash upon enabling shader

### ISSUE THREAD

**Issue by Gymyk** [Null-MC/Shrimple#54]
Game crashes with this error message whenever attempting to enable the shader.

deferred3.fsh: deferred3.fsh: ERROR: 0:269: 'fogStart' : undeclared identifier 
ERROR: 0:269: '' : compilation terminated 
ERROR: 2 compilation errors.  No code generated.

**Comment by null511** [comment]
I'm assuming this is Release 0.10, since the latest dev version removed/replaced that program. Try using the latest dev version: https://github.com/Null-MC/Shrimple/archive/refs/heads/main.zip
