### ISSUE TITLE
initializer of const variable `worldSunColor' must be a constant expression

### ISSUE THREAD

**Issue by PhilipRoman** [Null-MC/Shrimple#55]
```
begin1.csh: begin1.csh: 0:441(28): error: initializer of const variable `worldSunColor' must be a constant expression
0:442(32): error: initializer of const variable `worldHorizonColor' must be a constant expression
0:443(29): error: initializer of const variable `worldMoonColor' must be a constant expression
```

Not familiar with shaders but I guess RGBToLinear is not considered a built in function and so according to https://www.khronos.org/opengl/wiki/Core_Language_(GLSL)#Constant_expression cannot be used to initialize a const variable

**Comment by null511** [comment]
I'll fix it; usually that's fine but I'm guessing you have an AMD card, which is really picky about const.
