### ISSUE TITLE
[1.19.2] Crash on enable with iris 1.6

### ISSUE THREAD

**Issue by itsdinkd** [Null-MC/Shrimple#6]
Attempted to use in my modpack AQM2. 

Crashed immediately after enabling.

Version 0.7 Shrimple
 https://gist.github.com/itsdinkd/b7c0921d67240bf07ecb384346e3f9b9

**Comment by null511** [comment]
- This looks like a mod is conflicting with Iris and not related to the shader at all.
- Shrimple doesn't allow redistribution with owner permission.
- You need the latest Iris 1.6.0 if you want to use colored lighting/ray-tracing.
- The next official release, and first public 1.0 release, will be within next few days.

**Comment by null511** [comment]
I didn't say whether I was interested or not, but redistributing other peoples products when the license prohibits it is illegal.

> Not a mod conflict as I was testing a different shader before I switched to
yours.
Also not relevant; I'm assuming you don't know how to read a stack trace because it tells you what the conflict is. Mod mixins are not shader related, and there is no error here related to Shrimple.

**Comment by itsdinkd** [comment]
I never said I was shipping it out. I said **i attempted to use it**. Whole purpose of me mentioning my modpack was so that you could be aware of what to use for your tests if it went that far. 

Second, your shader is on Curseforge. adding it to a curseforge modpack is not redistributing and does not break any laws. your definition is widely loose. 

yes I know how to read a stacktrace. your shader obviously caused issues with iris. there might be a conflict somewhere, but it is stemming for your shader pack.

**Comment by null511** [comment]
Feel free to revisit/open a new issue once you have an error log without the other mods installed, as there's nothing in your current log related to shrimple that I can work with.
