### ISSUE TITLE
This shader causes me to crash upon enabling it

### ISSUE THREAD

**Issue by Dongloid** [Null-MC/Shrimple#63]
When I first downloaded this shaderpack, it worked, and after fiddling around with a few others I figured this one would be preferable. Only to have it crash whenever I try to use it.

---- Minecraft Crash Report ----
// I feel sad now :(

Time: 2024-01-10 00:55:19
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_284.method_35660()" because "shader.field_29470" is null
	at net.diebuddies.render.OceanRenderer.renderOcean(OceanRenderer.java:391)
	at net.diebuddies.render.OceanRenderer.render(OceanRenderer.java:158)
	at net.diebuddies.render.LiquidRenderer.render(LiquidRenderer.java:86)
	at net.diebuddies.render.MainRenderer.renderLiquid(MainRenderer.java:725)
	at net.minecraft.class_761.handler$ekk000$physicsmod$renderLiquid(class_761.java:13963)
	at net.minecraft.class_761.method_3251(class_761.java)
	at net.minecraft.class_761.method_22710(class_761.java:1497)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.diebuddies.render.OceanRenderer.renderOcean(OceanRenderer.java:391)
	at net.diebuddies.render.OceanRenderer.render(OceanRenderer.java:158)
	at net.diebuddies.render.LiquidRenderer.render(LiquidRenderer.java:86)
	at net.diebuddies.render.MainRenderer.renderLiquid(MainRenderer.java:725)
	at net.minecraft.class_761.handler$ekk000$physicsmod$renderLiquid(class_761.java:13963)
	at net.minecraft.class_761.method_3251(class_761.java)
	at net.minecraft.class_761.method_22710(class_761.java:1497)
	at net.minecraft.class_757.method_3188(class_757.java:1110)

-- Affected level --
Details:
	All players: 1 total; [class_746['Damndood'/125646, l='ClientLevel', x=1323.31, y=75.00, z=2260.30]]
	Chunk stats: 1024, 275
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,114,0), Section: (at 0,2,0 in 0,7,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 8776552 game time, 2218092 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, minecraft:physicsmod, fabric, file/Armaments+of+Legend+Small+Package.zip, PFM-Runtime-RP, file/FA+All_Extensions-v1.2.zip, file/Hyper_Realistic_Sky_[v1.14].zip, file/Alacrity.zip, file/Cobblemon Interface b0.8.4.zip, Moonlight Mods Dynamic Assets, diagonalblocks:default_block_models

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2896241480 bytes (2762 MiB) / 8522825728 bytes (8128 MiB) up to 8522825728 bytes (8128 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: Virtual Desktop Monitor
	Graphics card #0 vendor: Virtual Desktop, Inc.
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=15.39.56.845
	Graphics card #1 name: NVIDIA GeForce RTX 2060 SUPER
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x1f06
	Graphics card #1 versionInfo: DriverVersion=31.0.15.4633
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 36427.93
	Virtual memory used (MB): 28293.78
	Swap memory total (MB): 20137.17
	Swap memory used (MB): 2399.16
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8128m -Xms256m
	Fabric Mods: 
		another_furniture: Another Furniture 1.20.1-3.0.1
		appleskin: AppleSkin 2.5.1+mc1.20
		archers: Archers (RPG Series) 1.0.6+1.20.1
			com_github_zsoltmolnarrr_tinyconfig: TinyConfig 2.3.2
			structure_pool_api: Structure Pool API 1.0+1.20.1
		architectury: Architectury 9.1.12
		azurelib: AzureLib 2.0.18
		azurelibarmor: AzureLib Armor 2.0.3
		bbca: Blackwing's Better Combat Addon 1.0.0
		betterarcheology: Better Archeology 1.1.0
		bettercombat: Better Combat 1.8.3+1.20.1
		betterdeserttemples: YUNG's Better Desert Temples 1.20-Fabric-3.0.3
			org_reflections_reflections: reflections 0.10.2
		betterdungeons: YUNG's Better Dungeons 1.20-Fabric-4.0.3
		betterendisland: YUNG's Better End Island 1.20-Fabric-2.0.4
		betterfortresses: YUNG's Better Nether Fortresses 1.20-Fabric-2.0.5
		betterjungletemples: YUNG's Better Jungle Temples 1.20-Fabric-2.0.4
		bettermineshafts: YUNG's Better Mineshafts 1.20-Fabric-4.0.4
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.20-Fabric-3.0.4
		betterstrongholds: YUNG's Better Strongholds 1.20-Fabric-4.0.3
		betterwitchhuts: YUNG's Better Witch Huts 1.20-Fabric-3.0.3
		bookshelf: Bookshelf 20.1.8
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.11.0
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.11.0
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.11.0
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.11.0
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.11.0
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.11.0
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.11.0
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.11.0
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.11.0
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.11.0
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.11.0
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.11.0
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.11.0
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.11.0
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.11.0
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.11.0
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.11.0
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.11.0
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.0
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.11.0
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.0
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		cameraoverhaul: Camera Overhaul 1.4.0-fabric-universal
		chunky: Chunky 1.3.92
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		cobblemon: Cobblemon 1.4.0+1.20.1
		cobblemon_capturexp: Cobblemon Capture EXP 1.4-fabric-1.0.2
		cobblemonintegrations: Cobblemon Integrations 1.0.4
		cobblemonmikeskills: cobblemonmikeskills 1.0.1+1.20.1
		cobblemounts: CobbleMounts 1.2.1
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		cobblepedia: Cobblepedia 0.5.2
		combatroll: Combat Roll 1.3.0+1.20.1
		continuity: Continuity 3.0.0-beta.4+1.20.1
		cristellib: Cristel Lib 1.1.5
			blue_endless_jankson: jankson 1.2.3
		dehydration: Dehydration 1.3.5
		diagonalfences: Diagonal Fences 8.1.3
			diagonalblocks: Diagonal Blocks 8.0.2
		distanthorizons: Distant Horizons 2.0.1-a
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
		dungeon_difficulty: Dungeon Difficulty 2.0.5+1.20.1
		enchanted-vertical-slabs: Enchanted Vertical Slabs 1.9.1
		enhancedblockentities: Enhanced Block Entities 0.9+1.20
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			spruceui: SpruceUI 5.0.0+1.20
		entity_model_features: Entity Model Features 1.2
		entity_texture_features: Entity Texture Features 5.0
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20.1
		everycomp: Every Compat 1.20-2.6.18
		expanded_ecosphere: Expanded Ecosphere 3.2.3
		fabric-api: Fabric API 0.90.7+1.20.1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.12+215bbe9677
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.10+57aed33f77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.2+d7b148e077
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.39+ae9f657a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.11+d7b148e077
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.0+96dfa95977
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.44+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.8+d7b148e077
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.2+4ee0bc6077
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.0+39a511ba77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.0+39a511ba77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.6+d7b148e077
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.2+1bc31aeb77
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.17+kotlin.1.9.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.2
		fabricloader: Fabric Loader 0.15.3
			mixinextras: MixinExtras 0.3.2
		fabricskyboxes: FabricSkyBoxes 0.7.3+mc1.20.1
		farmersdelight: Farmer's Delight 1.20.1-1.4.3
		ferritecore: FerriteCore 6.0.1
		fightorflight: Cobblemon Fight or Flight Fabric 0.5.0
		forgeconfigapiport: Forge Config API Port 8.0.0
		friendlyfire: FriendlyFire 18.0.5
		geckolib: GeckoLib 4 4.3.1
			com_eliotlash_mclib_mclib: mclib 20
		grapplemod: Grappling Hook Mod 1.20-v1.7
		hwg: Happiness is a Warm Gun 2.0.1
		immediatelyfast: ImmediatelyFast 1.2.7+1.20.2
			net_lenni0451_reflect: Reflect 1.3.0
		immersive_paintings: Immersive Paintings 0.6.7+1.20.1
		indium: Indium 1.0.27+mc1.20.1
		iris: Iris 1.6.11
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		jade: Jade 11.6.4
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 15.2.0.27
		jewelry: Jewelry (RPG Series) 1.2.2+1.20.1
		jobsaddon: JobsAddon 1.1.5
		levelz: LevelZ 1.4.12
		libz: LibZ 1.0.3
			com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.15.2
			com_fasterxml_jackson_core_jackson-core: jackson-core 2.15.2
			com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.15.2
		lithium: Lithium 0.11.2
		lootr: Lootr 0.7.29.75
		magistuarmory: Epic Knights Mod 8.11
		magistuarmoryaddon: Epic Knights: Addon 1.3
		mca: Minecraft Comes Alive 7.5.11+1.20.1
		mcwbridges: Macaw's Bridges 2.1.0
		mcwdoors: Macaw's Doors 1.1.0
		mcwfences: Macaw's Fences and Walls 1.0.7
		mcwfurnitures: Macaw's Furniture 3.2.1
		mcwlights: Macaw's Lights and Lamps 1.0.6
		mcwpaintings: Macaw's Paintings 1.0.5
		mcwwindows: Macaw's Windows 2.2.1
		minecraft: Minecraft 1.20.1
		modernfix: ModernFix 5.9.3+mc1.20.1
		modmenu: Mod Menu 7.2.2
		moonlight: Moonlight 1.20-2.8.78
		moreculling: More Culling 1.20.1-0.19.0
			conditional-mixin: conditional mixin 0.3.2
		morediscs: More Music Discs 1.20.1-32-fabric
		mr_mine_treasure: Mine Treasure 1.3.2
		nochatreports: No Chat Reports 1.20.1-v2.2.2
		noisium: Noisium 1.0.2+mc1.20.x
		paladins: Paladins & Priests (RPG Series) 1.0.4+1.20.1
		patchouli: Patchouli 1.20.1-84-FABRIC
			fiber: fiber 0.23.0-2
		patchoulibutton: PachouliButton 1.0.2
		pfm: Paladin's Furniture 1.2.0
		physicsmod: Physics Mod 3.0.10
		player-animator: Player Animator 1.0.2-rc1+1.20
		polymorph: Polymorph 0.49.1+1.20.1
			cardinal-components-base: Cardinal Components API (base) 5.2.1
			cardinal-components-block: Cardinal Components API (blocks) 5.2.1
			cardinal-components-entity: Cardinal Components API (entities) 5.2.1
			cardinal-components-item: Cardinal Components API (items) 5.2.1
			spectrelib: SpectreLib 0.13.14+1.20.1
		projectile_damage: Projectile Damage Attribute 3.2.2+1.20.1
		puffish_skills: Pufferfish's Skills 0.10.0
		puzzleslib: Puzzles Lib 8.1.11
			puzzlesaccessapi: Puzzles Access Api 8.0.7
		raised: Raised 3.1.0
		regions_unexplored: Regions Unexplored 0.5.3.2+1.20.1
			completeconfig-base: completeconfig-base 2.5.2
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.5.2
		rocks: This Rocks! 1.7.1
			midnightlib: MidnightLib 1.4.1
		runes: Runes 0.9.10+1.20.1
		simplyskills: SimplySkills 1.0.0+1.20.1
		simplyswords: Simply Swords 1.51.5-1.20.1
		skinlayers: 3d Skin Layers 1.5.4-mc1.20.1
		slavicarmory: Epic Knights: Slavic Armory 1.1
		smartbrainlib: SmartBrainLib 1.13
		sodium: Sodium 0.5.3
		soulsweapons: Marium's Soulslike Weaponry 1.0.2-1.20-fabric
		sound_physics_remastered: Sound Physics Remastered 1.20.1-1.1.2
		spell_engine: Spell Engine 0.12.4+1.20.1
		spell_power: Spell Power Attribute 0.9.19+1.20.1
		spellbladenext: Spellblades and Such 1.3
		supplementaries: Supplementaries 1.20-2.7.15
			mixinsquared: MixinSquared 0.1.1
		terrablender: TerraBlender 3.0.0.169
		threadtweak: ThreadTweak 1.20.2-0.1.1
		travelersbackpack: Traveler's Backpack 1.20.1-9.1.9
		travelerstitles: Traveler's Titles 1.20-Fabric-4.0.1
		trinkets: Trinkets 3.7.1
		valhelsia_core: Valhelsia Core 1.1.1
		valhelsia_furniture: Valhelsia Furniture 1.1.2
		vmp: Very Many Players 0.2.0+beta.7.102
		wizards: Wizards (RPG Series) 1.0.4+1.20.1
		wwoo: William Wythers' Overhauled Overworld 2.0.0
		xaerominimap: Xaero's Minimap 23.9.3
		xaeroworldmap: Xaero's World Map 1.37.2
		yungsapi: YUNG's API 1.20-Fabric-4.0.2
			org_javassist_javassist: javassist 3.29.2-GA
		yungsbridges: YUNG's Bridges 1.20-Fabric-4.0.3
		yungsextras: YUNG's Extras 1.20-Fabric-4.0.3
	Loaded Shaderpack: Shrimple-main.zip
		Profile: SHADOWS (+0 options changed by user)
	Launched Version: fabric-loader-0.15.3-1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 2060 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 546.33, NVIDIA Corporation
	Window size: 2048x1152
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. <size> must be positive.' x 3
id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. <program> object is not successfully linked, or is not a program object.' x 215
id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. <program> has not been linked, or is not a program object.' x 1
id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. <program> object is not successfully linked, or is not a program object.' x 2
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, minecraft:physicsmod (incompatible), fabric, file/Armaments+of+Legend+Small+Package.zip, pfm-asset-resources, file/FA+All_Extensions-v1.2.zip, file/Hyper_Realistic_Sky_[v1.14].zip (incompatible), file/Alacrity.zip, file/Cobblemon Interface b0.8.4.zip, Moonlight Mods Dynamic Assets
	Current Language: en_us
	CPU: 8x Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz

**Comment by null511** [comment]
This is a known bug with PhysicsMod that I can't work around. I've notified Haubna but I don't think they have any interest in investigating or fixing it. afaik, it's because the shader-patching PhyMod applies do not support geometry [or tessellation] shaders, which I use both of.

**Comment by Dongloid** [comment]
thanks for the reply man, I'll try to workaround it!
