### ISSUE TITLE
Block-lights flickering

### ISSUE THREAD

**Issue by PinguLinux** [Null-MC/Shrimple#64]
Block-lights flickers in the latest dev version on default settings and lighting mode set to "Ray-traced".

https://github.com/Null-MC/Shrimple/assets/55950650/4cf6ace2-9bbf-4b2c-a8f7-5db89b0cf1b7

Doesn't seem to happen to every block-light.

https://github.com/Null-MC/Shrimple/assets/55950650/1830d143-03e6-49de-b86d-53166ef7f20e

Mods:
- fabric-api-0.92.0+1.20.4
- sodium-fabric-mc1.20.3-0.5.5
- iris-mc1.20.4-1.6.14

Minecraft version: fabric 0.15.3 for Minecraft 1.20.4

**Comment by null511** [comment]
This should be fixed now, since the default settings were updated to trace every light. I removed RT accumulation to rely on TAA instead, but that didn't work out well; so I'll probably add accumulation back again soon.
