### ISSUE TITLE
Blank banner textures

### ISSUE THREAD

**Issue by IAdventurer01** [Null-MC/Shrimple#7]
When enabling either ray tracing or shadows, all banner textures in the world are removed and appear to be pure white banners.

![image](https://user-images.githubusercontent.com/18755087/231511648-5dc9e30c-91cc-463a-89d4-a085abb743cf.png)

Using Iris 1.6 & sodium 0.4.10

**Comment by null511** [comment]
This is an Iris bug, it should now be fixed with Iris 1.6.1

**Comment by IAdventurer01** [comment]
Unfortunately it's not, but very well could still be an Iris issue.  Here's hoping to a fix in 1.6.2?

**Comment by IAdventurer01** [comment]
Appears to be fixed in v0.8
