### ISSUE TITLE
It doesn't have any colored lighting for me

### ISSUE THREAD

**Issue by Kimizuky** [Null-MC/Shrimple#72]
It doesn't have any colored lighting, ray traced shadows, and I remember it had sometime before I reset my pc, what is going on?

**Comment by Kimizuky** [comment]
![2024-03-18_14 39 17](https://github.com/Null-MC/Shrimple/assets/163897583/68ffceed-e17b-4185-99d4-ef242dba1066)

**Comment by null511** [comment]
I assume you're using the "Colored Lights" or "RTX" profile, right? Colored block-light isn't enabled by default. Otherwise post your settings.

**Comment by Kimizuky** [comment]
> I assume you're using the "Colored Lights" or "RTX" profile, right? Colored block-light isn't enabled by default. Otherwise post your settings.

Man I'm really sorry, I thought it would be on by default, I overlooked the settings, it's working now
