### ISSUE TITLE
Lighting flickers ALOT when going far underground, and glow berries don't emit any light.

### ISSUE THREAD

**Issue by biomseed** [Null-MC/Shrimple#8]
Title.

**Comment by biomseed** [comment]
This is with the latest version on modrinth by the way.

**Comment by null511** [comment]
Gonna need a bit more info...

- Can you tell if it's block-light that is flickering, and not sun/moon light leaking into caves?
 
- If it is block lights, then you're most likely near a lava pool/lake that is filling up the light bins. This is a know issue, you can work around it by disabling lava from dynamic lighting. You can also:
   + Reduce the Block Lighting > Advanced > Bin Size to 4 (this makes lists use a smaller block area)
   + Increase the Max Bin Lights count; this will reduce performance though

**Comment by null511** [comment]
Also worth noting the next release at east removes the flickering, you'll just have less lights if the list gets full

**Comment by biomseed** [comment]
> Gonna need a bit more info...
> 
> * Can you tell if it's block-light that is flickering, and not sun/moon light leaking into caves?
> * If it is block lights, then you're most likely near a lava pool/lake that is filling up the light bins. This is a know issue, you can work around it by disabling lava from dynamic lighting. You can also:
>   
>   * Reduce the Block Lighting > Advanced > Bin Size to 4 (this makes lists use a smaller block area)
>   * Increase the Max Bin Lights count; this will reduce performance though

For that first question, I literally cannot tell. It seems to just be broken lighting, and not related to lava because it's not near lava.
