### ISSUE TITLE
shadows flicker (TAA reduces the flickering)

### ISSUE THREAD

**Issue by unholypersona** [Null-MC/Shrimple#89]
https://github.com/Null-MC/Shrimple/assets/113929815/7f064d99-8f2a-4397-b97a-d37bd562338d

**Comment by null511** [comment]
Try the latest in-development version
https://github.com/Null-MC/Shrimple/archive/refs/heads/main.zip

**Comment by unholypersona** [comment]
yep, that seems to fix it, thank you!
